server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:  application:    name: api-gateway
  cloud:    gateway:      discovery:        locator:          enabled: true
      routes:      - id: employee-service
        uri: lb://employee-service
        predicates:        - Path=/api/employee/**
      - id: department-service
        uri: lb://department-service
        predicates:        - Path=/api/department/**
      - id: organizational-service
        uri: lb://organizational-service
        predicates:        - Path=/api/organization/**                              